### ISSUE TITLE
Документация по сборке проекта

### ISSUE THREAD

**Issue by gluhow** [makise-homura/reimu-docs-ru#1]
Попробовал запустить сборку проекта в Ubuntu 20.04 в соответствии с reimu-BUILD.md обнаружились небольшие проблемы

1. Не совсем логично располагать требования к установленым программам в разделе минимальных технических требований в ВК. Может быть лучше сделать раздел "До сборки" или перенести в сборку?
2. Для "голого" образа Ubuntu 20.04 мне потребовалось выполнить
sudo apt install libfdt1 libfdt-dev
sudo apt install g++ make gawk diffstat chrpath git
Может как команды их и добавить?
3. В п.6 мин требованиях "Также должны быть заданы (с помощью команды git config) следующие переменные:"
 * Я до этого не задавал переменные git, поэтому не было очевидно что надо только git config + указанная строка, тем более что так не сработало
 * Это надо делать либо с флагом --global (что не выглядит правильным), либо внутри скачанного репозитория, а репозиторий еще не скачан, т.к. скачивание идет в разделе "Процедура сборки", а до него еще дело не дошло
 * Указанные строки не сработали, а сработало следующим образом:
     - git config url.https://github.com/.insteadof git://github.com/
     - git config url.https://git.yoctoproject.org/git/.insteadof git://git.yoctoproject.org/
     - git config url.https://git.savannah.gnu.org/git/.insteadof git://git.savannah.gnu.org/

**Comment by makise-homura** [comment]
Добрый день! Вроде всё пофиксил. Теперь все эти вопросы должны быть прозрачно описаны в доке.
Если что не так - переоткройте issue.
